getwd()
setwd("C:/Users/Sineus/Desktop/essaie")
job<-read.csv("job_skills.csv", header = TRUE, stringsAsFactors = F)
head(job)
colnames(job)
class(job)
str(job)
library(tm)
install.packages(SentimentAnalysis)
library(SentimentAnalysis)

